### ISSUE TITLE
Sometimes gives Unknown Error

### ISSUE THREAD

**Issue by xMegaz** [Holfz/Steam-Account-Creator#2]
Well, after editing this source (adding login. modifying esthetics) when i generate the account after i solve the captcha, it says "unknown error"... Well, why does this happen?

**Comment by Holfz** [comment]
it's happend "sometimes" or "everytime" ?

**Comment by xMegaz** [comment]
Well I seem to fixed it running as administrator, thanks for the answer

Il giorno dom 27 gen 2019, 14:01 Wachirawich Ruangpatimakorn <
notifications@github.com> ha scritto:
