### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by suha-repo** [Holfz/Steam-Account-Creator#3]
Add proxy support on program and auto captcha with 2captcha.com??

**Comment by Holfz** [comment]
At now, you can use [this fork](
https://github.com/urmumusesmyhakerino/Steam-Account-Creator/) and replace my MailSystem.cs and compile it for using proxy support.

So, i will try how i can do for proxy support and autocaptcha soon (As say i don’t have experience with C# before...)
