### ISSUE TITLE
Max 3 accounts

### ISSUE THREAD

**Issue by luk27official** [Holfz/Steam-Account-Creator#5]
A maximum of 3 accounts can be created at one time, otherwise this function in MainForm.cs throws a System.ArgumentOutOfRangeException:
`        public void UpdateStatus(int i, string status)
        {
            BeginInvoke(new Action(() =>
            {
                dataAccounts.Rows[i].Cells[3].Value = status;
            }));
        }`

**Comment by sparkdz** [comment]
I opened 96 accounts on this version at the same time

**Comment by luk27official** [comment]
Well, it may work with the release version, I tried recompiling it. Commenting the line worked for me.
